version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      DYNAMO_ENDPOINT: http://localhost:8000
      AWS_ACCESS_KEY_ID: dynamodb-user
      AWS_SECRET_ACCESS_KEY: dynamodb-password
      AWS_REGION: eu-central-1
    command: [ "-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb" ]
  dynamodb-admin-local:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin-local
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: dynamodb-user
      AWS_SECRET_ACCESS_KEY: dynamodb-password
    depends_on:
      - dynamodb-local
  postgresql-local:
    image: postgres
    container_name: postgresql-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql-user
      POSTGRES_PASSWORD: postgresql-password
      POSTGRES_DB: tdd-complete-guide-db
  app:
    container_name: app-tdd-complete-guide
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-local